name: Request Feature
description: Request A Feature
title: "[Feature Request]: "
labels: ["Request"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request a feature or something else!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: What do you want to request?
      description: "Note: This is only a scratch project. Scratch project cant support websites. Please Do Not Request Websites."
      placeholder: Tell Us Something To Add!
      value: "Request Something"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code Of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
